[".config/nvim"]
  type = "git-repo"
  url = "https://github.com/LazyVim/starter"
  refreshPeriod = "48h"
[".emacs.d"]
  type = "git-repo"
  url = "https://github.com/syl20bnr/spacemacs.git"
  refreshPeriod = "48h"
[".gdbinit"]
  type = "file"
  url = "https://git.io/.gdbinit"
  refreshPeriod = "168h"
[".gdbinit.d/llvm/prettyprinters.py"]
  type = "file"
  url = "https://raw.githubusercontent.com/llvm/llvm-project/main/llvm/utils/gdb-scripts/prettyprinters.py"
  refreshPeriod = "168h"
[".config/kitty/kitty-themes"]
  type = "git-repo"
  url = "https://github.com/dexpota/kitty-themes.git"
  refreshPeriod = "0"
["AppData/Local/services/vs-code-server/vscodeserver.exe"]
  type = "file"
  url = "https://github.com/winsw/winsw/releases/download/v2.12.0/WinSW-x64.exe"
  refreshPeriod = "0"

